apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-frontend
  template:
    metadata:
      labels:
        app: gs-frontend
    spec:
      containers:
      - name: gs-frontend
        image: acrgdvivo.azurecr.io/gs-frontend:latest